import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Moon, LogIn, UserPlus, Info, Check, ExternalLink, ShieldCheck, Mail, KeyRound, RefreshCw, ArrowLeft, Clock, Zap, CheckCircle2, Send } from 'lucide-react';
import { auth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, signInWithRedirect, getRedirectResult } from '../lib/supabaseAuth';
import { db, doc, setDoc, getDoc } from '../lib/supabaseFirestore';
import { sendVerificationCodeToEmail, verifyVerificationCode, getWebmailUrl } from '../lib/emailService';

interface AuthScreenProps { onAuthSuccess: (user: any) => void; pendingTwoFactorUser?: any | null; onSignOut?: () => void; }
const PRESET_AVATARS = [
  { name: 'Starry', url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80' },
  { name: 'Neon', url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80' },
  { name: 'Cosmic', url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80' },
  { name: 'Nocturnal', url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80' },
  { name: 'Wanderer', url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80' },
  { name: 'Solitary', url: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=150&auto=format&fit=crop&q=80' },
];
const TRUSTED_EMAIL_DOMAINS = ['gmail.com','googlemail.com','google.com','outlook.com','hotmail.com','live.com','msn.com','microsoft.com','proton.me','protonmail.com','pm.me','icloud.com','me.com','mac.com','yahoo.com','ymail.com','zoho.com','zohomail.com','aol.com','fastmail.com','tuta.com','tutanota.com','gmx.com','mail.com'];
function isEmailDomainAuthorized(emailAddress: string) { const clean=emailAddress.trim().toLowerCase(); const at=clean.lastIndexOf('@'); if(at===-1||at===clean.length-1)return false; const domain=clean.slice(at+1); if(TRUSTED_EMAIL_DOMAINS.includes(domain))return true; if(domain.endsWith('.edu')||domain.includes('.edu.')||domain.endsWith('.ac.uk'))return true; if(['mailinator.com','tempmail.com','guerrillamail.com','10minutemail.com','trashmail.com','yopmail.com','sharklasers.com','fake.com','test.com','example.com'].includes(domain))return false; return /^[a-z0-9-]+(\.[a-z0-9-]+)+$/.test(domain)&&domain.length>=4; }

export default function AuthScreen({ onAuthSuccess, pendingTwoFactorUser, onSignOut }: AuthScreenProps) {
  const [isSignUp,setIsSignUp]=useState(false),[email,setEmail]=useState(pendingTwoFactorUser?.email||''),[password,setPassword]=useState('');
  const [error,setError]=useState(''),[loading,setLoading]=useState(false),[popupBlocked,setPopupBlocked]=useState(false),[showSignUpSuggest,setShowSignUpSuggest]=useState(false);
  const [twoFactorStage,setTwoFactorStage]=useState(Boolean(pendingTwoFactorUser)),[twoFactorEmail,setTwoFactorEmail]=useState(pendingTwoFactorUser?.email||''),[pendingProfile,setPendingProfile]=useState<any|null>(pendingTwoFactorUser||null);
  const [otpDigits,setOtpDigits]=useState<string[]>(['','','','','','']),[otpError,setOtpError]=useState(''),[otpSuccess,setOtpSuccess]=useState(false),[timeLeft,setTimeLeft]=useState(600),[resendCooldown,setResendCooldown]=useState(30),[emailSending,setEmailSending]=useState(false),[emailSentTimestamp,setEmailSentTimestamp]=useState('');
  const [webmailData,setWebmailData]=useState<{name:string;url:string;searchUrl:string}|null>(null),[verifying,setVerifying]=useState(false);
  const otpInputRefs=[useRef<HTMLInputElement>(null),useRef<HTMLInputElement>(null),useRef<HTMLInputElement>(null),useRef<HTMLInputElement>(null),useRef<HTMLInputElement>(null),useRef<HTMLInputElement>(null)];
  const bio='Chasing midnight dreams and quiet frequencies. 🌌☕';

  const initiateTwoFactorVerification=async(profileData:any,userEmail:string)=>{const clean=(userEmail||profileData?.email||email).trim().toLowerCase();setPendingProfile(profileData);setTwoFactorEmail(clean);setOtpDigits(['','','','','','']);setOtpError('');setOtpSuccess(false);setTimeLeft(600);setResendCooldown(30);setTwoFactorStage(true);setEmailSending(true);setWebmailData(getWebmailUrl(clean));try{const result=await sendVerificationCodeToEmail(clean,undefined,profileData);setEmailSentTimestamp(new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));setWebmailData({name:result.providerName,url:result.webmailUrl,searchUrl:result.webmailUrl});}catch(e){setOtpError(e instanceof Error?e.message:'Could not send verification email.');}finally{setEmailSending(false)}};
  useEffect(()=>{if(pendingTwoFactorUser&&!twoFactorStage)initiateTwoFactorVerification(pendingTwoFactorUser,pendingTwoFactorUser.email||email)},[pendingTwoFactorUser]);
  useEffect(()=>{if(!twoFactorStage)return;const timer=setInterval(()=>{setTimeLeft(p=>p>0?p-1:0);setResendCooldown(p=>p>0?p-1:0)},1000);return()=>clearInterval(timer)},[twoFactorStage]);
  useEffect(()=>{if(twoFactorStage)setTimeout(()=>otpInputRefs[0].current?.focus(),300)},[twoFactorStage]);
  const handleVerifyOtp=async(codeToCheck?:string)=>{const code=(codeToCheck||otpDigits.join('')).trim();if(code.length!==6){setOtpError('Please enter all 6 digits of the code.');return}if(timeLeft<=0){setOtpError('Verification code has expired. Please click Resend Code.');return}setVerifying(true);setOtpError('');try{await verifyVerificationCode(twoFactorEmail,code);setOtpSuccess(true);if(pendingProfile?.uid)sessionStorage.setItem(`nightgram_2fa_${pendingProfile.uid}`,'true');setTimeout(()=>onAuthSuccess(pendingProfile),500)}catch(e){setOtpError(e instanceof Error?e.message:'Invalid verification code.')}finally{setVerifying(false)}};
  const handleOtpDigitChange=(index:number,val:string)=>{const digit=val.replace(/\D/g,'').slice(-1),next=[...otpDigits];next[index]=digit;setOtpDigits(next);setOtpError('');if(digit&&index<5)otpInputRefs[index+1].current?.focus();if(next.every(Boolean))handleVerifyOtp(next.join(''))};
  const handleOtpKeyDown=(index:number,e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==='Backspace'&&!otpDigits[index]&&index>0){const next=[...otpDigits];next[index-1]='';setOtpDigits(next);otpInputRefs[index-1].current?.focus()}else if(e.key==='ArrowLeft'&&index>0)otpInputRefs[index-1].current?.focus();else if(e.key==='ArrowRight'&&index<5)otpInputRefs[index+1].current?.focus()};
  const handleOtpPaste=(e:React.ClipboardEvent)=>{e.preventDefault();const pasted=e.clipboardData.getData('text').replace(/\D/g,'').slice(0,6);if(!pasted)return;const next=['','','','','',''];for(let i=0;i<pasted.length;i++)next[i]=pasted[i];setOtpDigits(next);if(pasted.length===6)handleVerifyOtp(pasted);else otpInputRefs[pasted.length].current?.focus()};
  const handleResendCode=async()=>{if(resendCooldown>0||emailSending)return;setOtpDigits(['','','','','','']);setOtpError('');setTimeLeft(600);setResendCooldown(30);setEmailSending(true);try{const result=await sendVerificationCodeToEmail(twoFactorEmail,undefined,pendingProfile);setEmailSentTimestamp(new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));setWebmailData({name:result.providerName,url:result.webmailUrl,searchUrl:result.webmailUrl})}catch(e){setOtpError(e instanceof Error?e.message:'Could not resend verification email.')}finally{setEmailSending(false)}otpInputRefs[0].current?.focus()};
  const handleCancelTwoFactor=()=>{setTwoFactorStage(false);setPendingProfile(null);setOtpDigits(['','','','','','']);setOtpError('');setOtpSuccess(false);if(onSignOut)onSignOut()};
  const cleanEmail=(u:any)=>String(u?.email||'').trim().toLowerCase();
  const handleUserDocCheck=async(user:any)=>{const ref=doc(db,'users',user.uid),snap=await getDoc(ref);if(snap.exists()){const profile=snap.data();await initiateTwoFactorVerification(profile,user.email||cleanEmail(user))}else{const base=(user.email?.split('@')[0]||'dreamer').trim().toLowerCase().replace(/[^a-z0-9_]/g,''),uname=base+Math.floor(Math.random()*1000),profile={uid:user.uid,email:user.email||'',username:uname,displayName:user.displayName||'A Midnight Dreamer',avatar:user.photoURL||PRESET_AVATARS[0].url,bio,followers:0,following:0,stars:0,createdAt:new Date().toISOString()};await setDoc(doc(db,'usernames',uname),{uid:user.uid});await setDoc(ref,profile);await initiateTwoFactorVerification(profile,user.email||cleanEmail(user))}};
  const handleEmailAuth=async()=>{setError('');setShowSignUpSuggest(false);if(!isEmailDomainAuthorized(email)){setError('Please use a valid email address from a supported or legitimate domain.');return}setLoading(true);try{const result=isSignUp?await createUserWithEmailAndPassword(auth,email,password):await signInWithEmailAndPassword(auth,email,password);await handleUserDocCheck(result.user)}catch(e:any){setError(e?.message||'Authentication failed.');if(!isSignUp&&/invalid login credentials|user not found/i.test(e?.message||''))setShowSignUpSuggest(true)}finally{setLoading(false)}};
  const handleGoogle=async()=>{setError('');setPopupBlocked(false);setLoading(true);try{await signInWithPopup()}catch(e:any){if(e?.message?.toLowerCase().includes('popup')){setPopupBlocked(true);try{await signInWithRedirect()}catch(err:any){setError(err?.message||'Google sign-in failed.')}}else setError(e?.message||'Google sign-in failed.')}finally{setLoading(false)}};
  useEffect(()=>{getRedirectResult().then(r=>{if(r?.user)handleUserDocCheck(r.user)}).catch(e=>setError(e?.message||'Google sign-in failed.'))},[]);

  if(twoFactorStage)return <div className="min-h-screen bg-black text-white flex items-center justify-center p-4"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="w-full max-w-md rounded-3xl border border-white/10 bg-zinc-950 p-8 shadow-2xl"><div className="flex items-center gap-3 mb-6"><div className="rounded-2xl bg-white/10 p-3"><ShieldCheck/></div><div><h1 className="text-2xl font-bold">Verify your account</h1><p className="text-sm text-zinc-400">We sent a 6-digit code to {twoFactorEmail}</p></div></div>{emailSending&&<p className="text-sm text-zinc-400 mb-4">Sending verification email…</p>}{emailSentTimestamp&&!emailSending&&<p className="text-sm text-zinc-400 mb-4">Email sent at {emailSentTimestamp}.</p>}<div className="flex gap-2 justify-center mb-5">{otpDigits.map((digit,i)=><input key={i} ref={otpInputRefs[i]} value={digit} onChange={e=>handleOtpDigitChange(i,e.target.value)} onKeyDown={e=>handleOtpKeyDown(i,e)} onPaste={handleOtpPaste} inputMode="numeric" maxLength={1} disabled={verifying||otpSuccess} className="w-11 h-14 rounded-xl bg-white/5 border border-white/10 text-center text-xl font-bold outline-none focus:border-white/40" aria-label={`Verification digit ${i+1}`}/>)}</div>{otpError&&<p className="text-sm text-red-400 text-center mb-4">{otpError}</p>}{otpSuccess&&<p className="text-sm text-green-400 text-center mb-4">Verified successfully.</p>}<button disabled={verifying||otpSuccess} onClick={()=>handleVerifyOtp()} className="w-full rounded-xl bg-white text-black py-3 font-semibold disabled:opacity-50">{verifying?'Verifying…':otpSuccess?'Verified':'Verify code'}</button><button disabled={resendCooldown>0||emailSending} onClick={handleResendCode} className="w-full mt-3 rounded-xl border border-white/10 py-3 disabled:opacity-40">{emailSending?'Sending…':resendCooldown>0?`Resend in ${resendCooldown}s`:'Resend code'}</button>{webmailData&&<a href={webmailData.searchUrl} target="_blank" rel="noreferrer" className="mt-4 flex items-center justify-center gap-2 text-sm text-zinc-300 hover:text-white"><Mail size={16}/> Open {webmailData.name}<ExternalLink size={14}/></a>}<button onClick={handleCancelTwoFactor} className="mt-5 w-full text-sm text-zinc-500 hover:text-white flex items-center justify-center gap-2"><ArrowLeft size={15}/> Back to sign in</button></motion.div></div>;
  return <div className="min-h-screen bg-black text-white flex items-center justify-center p-4"><AnimatePresence mode="wait"><motion.div key={isSignUp?'signup':'login'} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="w-full max-w-md rounded-3xl border border-white/10 bg-zinc-950 p-8 shadow-2xl"><div className="flex items-center gap-3 mb-8"><div className="rounded-2xl bg-white/10 p-3"><Moon/></div><div><h1 className="text-3xl font-bold">Nightgram</h1><p className="text-zinc-400">{isSignUp?'Create your account':'Welcome back'}</p></div></div><div className="space-y-4"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" className="w-full rounded-xl bg-white/5 border border-white/10 p-3 outline-none"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" className="w-full rounded-xl bg-white/5 border border-white/10 p-3 outline-none"/>{error&&<p className="text-sm text-red-400">{error}</p>}{showSignUpSuggest&&<button onClick={()=>setIsSignUp(true)} className="text-sm text-zinc-300 underline">Create an account instead</button>}<button disabled={loading} onClick={handleEmailAuth} className="w-full rounded-xl bg-white text-black py-3 font-semibold disabled:opacity-50">{loading?(isSignUp?'Creating…':'Signing in…'):(isSignUp?'Create account':'Sign in')}</button><button disabled={loading} onClick={handleGoogle} className="w-full rounded-xl border border-white/10 py-3 font-semibold flex items-center justify-center gap-2"><LogIn size={17}/> Continue with Google</button>{popupBlocked&&<p className="text-xs text-zinc-500">Your browser blocked the Google popup. We will use redirect sign-in instead.</p>}<button onClick={()=>{setIsSignUp(v=>!v);setError('');setShowSignUpSuggest(false)}} className="w-full text-sm text-zinc-400 hover:text-white">{isSignUp?'Already have an account? Sign in':'New to Nightgram? Create an account'}</button></div></motion.div></AnimatePresence></div>;
}
